spring.application.name=newsfeed-project

jwt.secret.key=ajkhsdfiuqlqpo12305493erzxcmxznb16374379195uriwegkjf01953784iuyrtegwfjhadsvc1po32iwuejrqdacxxvzc8py78542ygucnrq10qwemnbziu34gvhwpqeioalzls48iughwek4786jvsbdds